version: '3.8'

services:
  maprclient:
    image: maprtech/pacc:7.2.0_9.1.0_ubuntu20_yarn_fuse_hbase_hive_spark_streams
    restart: unless-stopped

    volumes:
      - maprclient:/app:cached

    working_dir: /app
    # Overrides default command so things don't shut down after the process ends.
    # entrypoint: /app/docker-init.sh
    entrypoint: bash -c 'mv /etc/apt/sources.list.d/mapr* /tmp/; ( [ -f /docker-init.sh ] || wget -O /docker-init.sh https://raw.githubusercontent.com/erdincka/ez-start/master/docker-init.sh ) ; bash /docker-init.sh'
    # command: sleep infinity

    privileged: true
    cap_add:
      - SYS_ADMIN
      - SYS_RESOURCE

    devices:
      - /dev/fuse:/dev/fuse

    environment:
      MAPR_CLUSTER:
      MAPR_TZ: Europe/London
      MAPR_CLDB_HOSTS:
      MAPR_CONTAINER_USER: mapr
      MAPR_CONTAINER_PASSWORD:
      MAPR_CONTAINER_UID: 5000
      MAPR_CONTAINER_GID: 5000
      MAPR_CONTAINER_GROUP: mapr
      MAPR_TICKETFILE_LOCATION: /tmp/maprticket_0
      MAPR_MOUNT_PATH: /mapr
      LD_LIBRARY_PATH: /opt/mapr/lib
      JAVA_HOME: /usr/lib/jvm/java-11-openjdk-amd64
      SHELL: /bin/bash
      LC_ALL: en_US.UTF-8
      LANG: en_US.UTF-8
      LANGUAGE: en_US.UTF-8

volumes:
  maprclient: